### ISSUE TITLE
Serve application in subdirectory like http://example.org/cardgames

### ISSUE THREAD

**Issue by arthurlutz** [Pro1d/CovidCardGame#4]
First of congrats on a nice project ! Looking forward to using it to play remotely with friends and family. 

I'm trying to install it and host it on an server that already has some other web services running and I'd like to host it in a subdirectory behind an nginx proxy. It would be awesome to have a config file or environment variable to be able to do this. 

Tried to hack/modify https://github.com/Pro1d/CovidCardGame/blob/master/src/main.js directly by replacing `server.get('/',` by `server.get('/cardgames',` and it started working a bit, but then `/socket.io/` was not in the right place. 

By the way I'm trying to install on a machine managed by https://yunohost.org/#/ with a redirect app https://github.com/YunoHost-Apps/redirect_ynh that handles the nginx proxy configuration. Maybe, if time permits, I'll try to package the application for yunohost...

**Comment by Pro1d** [comment]
Hello! I really appreciate your interest for my project.

I'm very new to NodeJS and web related stuff. I barely know what is nginx and how web sockets work so it will be hard for me to answer properly. (I just run the server locally on my pc and forward the port on my internet box to make it public).

The architecture of this project is based on the [sample projects](https://github.com/lance-gg/tinygames) of [lance-gg](https://github.com/lance-gg/lance). So I would recommend you to search about how to host a lance-gg app with your desired config.

I've "savagely" coded this project on my spare time and I'm well aware that there is still a lot of work to do to make this project more conventional and publicly releasable (string internationalization, packaging, code quality, docs, etc...). Feel free to contribute or fork the repo to share your improvements.

**Comment by fbessou** [comment]
Hello there ! 
I managed to serve the application on a base path (https://github.com/Pro1d/CovidCardGame/pull/5)
I have a Yunohost instance and I would also be very interested to have CovidCardGame running on it ! :tada:

**Comment by fbessou** [comment]
@arthurlutz , feel free to reopen if it does not work on your deployment. :)

**Comment by arthurlutz** [comment]
Super! Works great ! I'll let you know know if I end up packaging it for yunohost. Thanks @fbessou for a quick and expert fix! :tada:
